namespace FlowOrchestrator.MappingProcessor;

/// <summary>
/// Represents a mapping definition.
/// </summary>
public class MappingDefinition
{
    /// <summary>
    /// Gets or sets the name of this mapping.
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the description of this mapping.
    /// </summary>
    public string Description { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the type of this mapping.
    /// </summary>
    public string MappingType { get; set; } = "json-map";

    /// <summary>
    /// Gets or sets the mapping definition content.
    /// </summary>
    public string MappingContent { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the source type.
    /// </summary>
    public string SourceType { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the target type.
    /// </summary>
    public string TargetType { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the version of this mapping.
    /// </summary>
    public string Version { get; set; } = "1.0.0";

    /// <summary>
    /// Gets or sets the author of this mapping.
    /// </summary>
    public string Author { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the creation date of this mapping.
    /// </summary>
    public DateTime CreationDate { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Gets or sets the last modified date of this mapping.
    /// </summary>
    public DateTime LastModifiedDate { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Gets or sets a value indicating whether this is an auto-generated mapping.
    /// </summary>
    public bool IsAutoGenerated { get; set; }

    /// <summary>
    /// Gets or sets the additional parameters for this mapping.
    /// </summary>
    public Dictionary<string, object> Parameters { get; set; } = new Dictionary<string, object>();
}
